name: CI Workflow

# تعريف الأحداث التي ستقوم بتشغيل الـ Workflow
on:
  push:
    branches:
      - master # الفرع الرئيسي
      - dev    # فرع التطوير

# تعريف المهام التي سيتم تشغيلها كجزء من الـ Workflow
jobs:
  notify_slack:
    # سيتم تشغيل هذا العمل على أحدث بيئة Ubuntu
    runs-on: ubuntu-latest

    steps:
    # الخطوة الأولى: تنزيل الكود من المستودع
    - name: تنزيل الكود من المستودع
      uses: actions/checkout@v3

    